// API TYPES
const GET_PROFILE = 'GET_PROFILE';
const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const SIGNOUT = 'SIGNOUT';

// IN APP TYPES
const SET_USER = 'SET_USER';
const SET_AUTH_STATE = 'SET_AUTH_STATE';

const types = { GET_PROFILE, LOGIN, SIGNUP, SIGNOUT, SET_USER, SET_AUTH_STATE };

export default types;
