// MODAL TYPES
const SET_LOGIN_MODAL = 'SET_LOGIN_MODAL';
const SET_SIGNUP_MODAL = 'SET_SIGNUP_MODAL';
const SET_CHANGE_PASSWORD_MODAL = 'SET_CHANGE_PASSWORD_MODAL';
const SET_RESET_PASSWORD_MODAL = 'SET_RESET_PASSWORD_MODAL';
const SET_INFO_MODAL = 'SET_INFO_MODAL';
const SET_PAYMENT_MODAL = 'SET_PAYMENT_MODAL';

// ALERT TYPES
const SET_ALERT = 'SET_ALERT';
const SET_ALERTS = 'SET_ALERTS';
const CLEAR_ALERTS = 'CLEAR_ALERTS';

// LANGUAGE TYPES
const SET_LANGUAGE = 'SET_LANGUAGE';

const SET_CCOPEN = 'SET_CCOPEN';

const types = {
  SET_LOGIN_MODAL,
  SET_SIGNUP_MODAL,
  SET_CHANGE_PASSWORD_MODAL,
  SET_RESET_PASSWORD_MODAL,
  SET_INFO_MODAL,
  SET_PAYMENT_MODAL,
  SET_ALERT,
  SET_ALERTS,
  CLEAR_ALERTS,
  SET_LANGUAGE,
  SET_CCOPEN,
};

export default types;
